[[redirects]]
  from = "/api"
  to = "https://frozen-garden-94356.herokuapp.com/"
  force = true
  status = 200

[[redirects]]
  from = "/auth/callback"
  to = "https://frozen-garden-94356.herokuapp.com/"
  force = true
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"